# Generated by Django 3.0.3 on 2020-04-11 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testing', '0002_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
